name: Generador de Piezas Juntoz

on:
  workflow_dispatch: # Permite ejecución manual
  schedule:
    # 10:00 AM hora de Perú (GMT-5) es 15:00 UTC
    - cron: '0 15 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automation
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python main.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          
          # Agregamos todas las imágenes generadas
          git add output/*.png || echo "No hay imágenes nuevas"
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Piezas generadas automáticamente: $(date)"
            git push
          else
            echo "Sin cambios detectados, nada que subir."
          fi
